platform:
  - x64

install:

build_script:
  - compile_cl.bat
  - cd test
  - compile_cl.bat
  - cd ..

test_script:
  - dir
  - C:\projects\voronoi\build\main.exe
  - C:\projects\voronoi\build\test.exe
